#ifndef SPACESIMULATION_ENVIRONMENT_H
#define SPACESIMULATION_ENVIRONMENT_H

#define SCALE 35

#define WIDTH SCALE*16
#define HEIGHT SCALE*9

#define RESOLUTION_X 1920
#define RESOLUTION_Y 1080

#define LIMIT_FRAMERATE 144

#endif
